FROM dependabot-script-local

COPY ["startup-script.prd.sh", "."]
RUN ["chmod", "+x", "startup-script.prd.sh"]

COPY ["event-handler.sh", "."]
RUN ["chmod", "+x", "event-handler.sh"]

ENTRYPOINT ["sh", "startup-script.prd.sh"]