name: Functions CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - DependabotOrchestrator/**
  pull_request:
    branches:
      - main
    paths: 
      - DependabotOrchestrator/**

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DependabotOrchestrator

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
